### ISSUE TITLE
function error in the testdbops.js

### ISSUE THREAD

**Issue by shail8989** [acloudfan/REST-API-Course-V2#2]
during the test of db connections, the function error occured .

apple@Aaron-Chong-MacBook-Air REST-API-Course-V2 % **node tests/TestDbOps.js
node:events:491**
      throw er; // Unhandled 'error' event
      ^

ReferenceError: criteria is not defined
    at /Users/apple/Downloads/REST-API-Course-V2/tests/TestDbOps.js:43:52
    at /Users/apple/Downloads/REST-API-Course-V2/db/vacations.js:38:9
    at /Users/apple/Downloads/REST-API-Course-V2/node_modules/mongoose/lib/model.js:5074:18
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
Emitted 'error' event on Function instance at:
    at /Users/apple/Downloads/REST-API-Course-V2/node_modules/mongoose/lib/model.js:5076:15
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
apple@Aaron-Chong-MacBook-Air REST-API-Course-V2 % 

can someone help on this >??

**Comment by shail8989** [comment]
its fixed by running the rpm install
